tenant_id                                       = ""  // Azure AD Tenant ID - This will be a GUID
prefix                                          = "datalz" //prefix and environment will be combined and used as a prefix for resource names
environment                                     = "dev" //prefix and environment will be combined and used as a prefix for resource names
location                                        = "southcentralus" // Azure region
vnetAddressPrefix                               = "10.1.0.0/16"
servicesSubnetAddressPrefix                     = "10.1.0.0/24"
databricksIntegrationPublicSubnetAddressPrefix  = "10.1.1.0/24"
databricksIntegrationPrivateSubnetAddressPrefix = "10.1.2.0/24"
databricksProductPublicSubnetAddressPrefix      = "10.1.3.0/24"
databricksProductPrivateSubnetAddressPrefix     = "10.1.4.0/24"
powerBiGatewaySubnetAddressPrefix               = "10.1.5.0/24"
dataIntegration001SubnetAddressPrefix           = "10.1.6.0/24"
dataIntegration002SubnetAddressPrefix           = "10.1.7.0/24"
dataProduct001SubnetAddressPrefix               = "10.1.8.0/24"
dataProduct002SubnetAddressPrefix               = "10.1.9.0/24"
dataManagementZoneVnetId                        = "/subscriptions/<SUBSCRIPTION ID>/resourceGroups/<RESOURCE GROUP NAME>/providers/Microsoft.Network/virtualNetworks/datamz-dev-network"
firewallPrivateIp                               = "10.0.0.4"
dnsServerAdresses                               = ["10.0.0.4"]
vmAdminUserName                                 = "<USERNAME FOR SERVICE>"
vmAdminPassword                                 = "<PASSWORD FOR SERVICE>"
sqlserverAdminGroupName                         = "<Azure AD Group Name>"
sqlAdminUserName                                = "<USERNAME FOR SERVICE>"
sqlAdminPassword                                = "<PASSWORD FOR SERVICE>"
sqlserverAdminGroupObjectID                     = "90e2f90b-dc0c-0000-0000-00000000000"
mysqlserverAdminGroupName                       = "<Azure AD Group Name>"
mysqlserverAdminGroupObjectID                   = "90e2f90b-dc0c-0000-0000-00000000000"

privateDnsZoneIdKeyVault          = "/subscriptions/<SUBSCRIPTION ID>/resourceGroups/<RESOURCE GROUP NAME>/providers/Microsoft.Network/privateDnsZones/privatelink.vaultcore.azure.net"
privateDnsZoneIdDataFactory       = "/subscriptions/<SUBSCRIPTION ID>/resourceGroups/<RESOURCE GROUP NAME>/providers/Microsoft.Network/privateDnsZones/privatelink.datafactory.azure.net"
privateDnsZoneIdDataFactoryPortal = "/subscriptions/<SUBSCRIPTION ID>/resourceGroups/<RESOURCE GROUP NAME>/providers/Microsoft.Network/privateDnsZones/privatelink.adf.azure.com"
privateDnsZoneIdDfs               = "/subscriptions/<SUBSCRIPTION ID>/resourceGroups/<RESOURCE GROUP NAME>/providers/Microsoft.Network/privateDnsZones/privatelink.dfs.core.windows.net"
privateDnsZoneIdBlob              = "/subscriptions/<SUBSCRIPTION ID>/resourceGroups/<RESOURCE GROUP NAME>/providers/Microsoft.Network/privateDnsZones/privatelink.blob.core.windows.net"
privateDnsZoneIdSqlServer         = "/subscriptions/<SUBSCRIPTION ID>/resourceGroups/<RESOURCE GROUP NAME>/providers/Microsoft.Network/privateDnsZones/privatelink.database.windows.net"
privateDnsZoneIdMySqlServer       = "/subscriptions/<SUBSCRIPTION ID>/resourceGroups/<RESOURCE GROUP NAME>/providers/Microsoft.Network/privateDnsZones/privatelink.mysql.database.azure.com"
privateDnsZoneIdEventhubNamespace = "/subscriptions/<SUBSCRIPTION ID>/resourceGroups/<RESOURCE GROUP NAME>/providers/Microsoft.Network/privateDnsZones/privatelink.servicebus.windows.net"
privateDnsZoneIdSynapseDev        = "/subscriptions/<SUBSCRIPTION ID>/resourceGroups/<RESOURCE GROUP NAME>/providers/Microsoft.Network/privateDnsZones/privatelink.dev.azuresynapse.net"
privateDnsZoneIdSynapseSql        = "/subscriptions/<SUBSCRIPTION ID>/resourceGroups/<RESOURCE GROUP NAME>/providers/Microsoft.Network/privateDnsZones/privatelink.sql.azuresynapse.net"

deploySelfHostedIntegrationRuntimes = true
datafactoryIds                      = [""]
